### ISSUE TITLE
Migrate from memcache to Redis

### ISSUE THREAD

**Issue by OndrejP** [RedisLabs/redis-migrate#1]

**Comment by itamarhaber** [comment]
@ondrep is there an actual issue with the utility or is this a feature request?

**Comment by OndrejP** [comment]
No, I don't think so. I only have 12 couchbase/membase boxes. Primary usage are session/cache. I need to migrate(dump/import) session from membase to redis. Loss on meantime are not important.

**Comment by OndrejP** [comment]
Dump form Memcached: http://lzone.de/dump+memcache+keys

**Comment by itamarhaber** [comment]
Since this isn't a real issue I'm closing it. Please feel free to contact me directly via email (itamar at redislabs.com) to continue the discussion and perhaps I'll be able to assist.
